document.writeln("");
document.writeln("    <nav class=\'gnav\'>");
document.writeln("        <div class=\'gnav-wrap\'>");
document.writeln("            <div class=\'gnav-container\'>");
document.writeln("                <ul class=\'gnav-main\'>");
document.writeln("                    <li class=\'gnav-main__item\'>");
document.writeln("                        <a href=\'sea.html\' class=\'gnav-anc\'>");
document.writeln("                            <img class=\'gnav-main__title\' src=\'images/common/title/sea_letter.png\' id=\'ocean\' alt=\'海\'>");
document.writeln("                            <span class=\'gnav-main__description\'>东指羲和能走马 海尘新生石山下</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'gnav-main__item\'>");
document.writeln("                        <a href=\'lake.html\' class=\'gnav-anc\'>");
document.writeln("                            <img class=\'gnav-main__title\' src=\'images/common/title/lake_letter.png\' id=\'lake\' alt=\'湖\'>");
document.writeln("                            <span class=\'gnav-main__description\'>沙漠回看清禁月 湖山应梦武林春</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("");
document.writeln("                    <li class=\'gnav-main__item\'>");
document.writeln("                        <a href=\'river.html\' class=\'gnav-anc\'>");
document.writeln("                            <img class=\'gnav-main__title\' src=\'images/common/title/river_letter.png\' id=\'river\' alt=\'川\'>");
document.writeln("                            <span class=\'gnav-main__description\'>百川东到海 何时复西归</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("");
document.writeln("                    <li class=\'gnav-main__item\'>");
document.writeln("                        <a href=\'mountain.html\' class=\'gnav-anc\'>");
document.writeln("                            <img class=\'gnav-main__title\' src=\'images/common/title/mountain_letter.png\' id=\'mountain\' alt=\'山\'>");
document.writeln("                            <span class=\'gnav-main__description\'>会当凌绝顶 一览众山小</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'gnav-news\'>");
document.writeln("                <ul class=\'gnav-news-list\'>");
document.writeln("                    <li class=\'gnav-news-list__item\'>");
document.writeln("                        <a href=\'sea.html\' class=\'anc-hover anc-hover_visible\'>");
document.writeln("                            <figure class=\'gnav-news-list__image\'>");
document.writeln("                                <img src=\'images/home/sea.jpg\' id=\'ocean\' alt=\'海\'>");
document.writeln("                            </figure>");
document.writeln("                            <h2 class=\'gnav-news__title\'>海阔凭鱼跃，天高任鸟飞。</h2>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("");
document.writeln("                    <li class=\'gnav-news-list__item\'>");
document.writeln("                        <a href=\'river.html\' class=\'anc-hover anc-hover_visible\'>");
document.writeln("                            <figure class=\'gnav-news-list__image\'>");
document.writeln("                                <img src=\'images/common/mountain_hua_01.jpg \' id=\'river\' alt=\'川\'>");
document.writeln("                            </figure>");
document.writeln("                            <h2 class=\'gnav-news__title\'>川从陕路去，河绕华阴流。</h2>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'gnav-news-list__item\'>");
document.writeln("                        <a href=\'lake.html\' class=\'anc-hover anc-hover_visible\'>");
document.writeln("                            <figure class=\'gnav-news-list__image\'>");
document.writeln("                                <img src=\'images/home/lake.JPG\' id=\'lake\' alt=\'湖\'>");
document.writeln("                            </figure>");
document.writeln("                            <h2 class=\'gnav-news__title\'>八月白露降，湖中水方老。</h2>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'gnav-news-list__item\'>");
document.writeln("                        <a href=\'mountain.html\' class=\'anc-hover anc-hover_visible\'>");
document.writeln("                            <figure class=\'gnav-news-list__image\'>");
document.writeln("                                <img src=\'images/home/mountain.jpg\' id=\'mountain\' alt=\'山\'>");
document.writeln("                            </figure>");
document.writeln("                            <h2 class=\'gnav-news__title\'>暮从碧山下，山月随人归。</h2>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </nav>");
document.writeln("    <header class=\'header\'>");
document.writeln("        <div class=\'header-wrap\'>");
document.writeln("            <div onclick=\'switchMode()\'>");
document.writeln("                <img src=\'./images/common/moon.svg\' id=\'moon\' alt=\'themeIcon\' class=\'themeIcon\'>");
document.writeln("            </div>");
document.writeln("            <div class=\'header-reserve\'>");
document.writeln("                <a href=\'#\' class=\'jp\'>回到顶部</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </header>");
document.writeln("");
document.writeln("<h1 class=\'head-logo\'>");
document.writeln("    <a href=\'./main.html\'>");
document.writeln("        <img class=\'head-logo_img\' src=\'./images/home/head_logo.png\' id=\'head_logo\' alt=\'hhhhh\'>");
document.writeln("    </a>");
document.writeln("</h1>");